### ISSUE TITLE
Deployment seems to do nothing

### ISSUE THREAD

**Issue by BrendanThompson** [weaveworks-plugins/scope-http-statistics#19]
Applying the `daemonset` on kubernetes 1.11.0, Ubuntu with a kernel of `4.15`. Once applied nothing happens, cannot see it in the Scope UI or in `/var/run/scope/plugins` on any Kubernetes nodes. However, I can see the `IOWait` plugin sitting there.

**Comment by XDMonkey** [comment]
+1
